[[nav]]
    name = "Knowledge Base"
    url = "/knowledge-base/"
    weight = 1

[[nav]]
    name = "awesome-pion"
    url = "https://github.com/pion/awesome-pion"
    weight = 2

[[nav]]
    name = "WebRTC for the Curious"
    url = "https://webrtcforthecurious.com"
    weight = 3

[[nav]]
    name = "Office Hours"
    url = "https://officehours.siobud.com"
    weight = 4

[[nav]]
    name = "Triage"
    url = "/triage/"
    weight = 5
